// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.1.0
// - protoc              v5.29.3
// source: service.proto

package servicepb

import (
	context "context"
	proto "go.unistack.org/micro-config-service/v4/proto"
	client "go.unistack.org/micro/v4/client"
)

var (
	ConfigName = "Config"
)

type ConfigClient interface {
	Load(ctx context.Context, req *proto.LoadRequest, opts ...client.CallOption) (*proto.LoadResponse, error)
	Save(ctx context.Context, req *proto.SaveRequest, opts ...client.CallOption) (*proto.SaveResponse, error)
}

type ConfigServer interface {
	Load(ctx context.Context, req *proto.LoadRequest, rsp *proto.LoadResponse) error
	Save(ctx context.Context, req *proto.SaveRequest, rsp *proto.SaveResponse) error
}
