// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.0.0
// - protoc              v3.21.12
// source: service.proto

package servicepb

import (
	context "context"
	proto "go.unistack.org/micro-config-service/v4/proto"
	v4 "go.unistack.org/micro-server-http/v4"
	client "go.unistack.org/micro/v4/client"
)

var (
	ConfigServiceName = "ConfigService"
)
var (
	ConfigServiceServerEndpoints = []v4.EndpointMetadata{}
)

type ConfigServiceClient interface {
	Load(ctx context.Context, req *proto.LoadRequest, opts ...client.CallOption) (*proto.LoadResponse, error)
	Save(ctx context.Context, req *proto.SaveRequest, opts ...client.CallOption) (*proto.SaveResponse, error)
}

type ConfigServiceServer interface {
	Load(ctx context.Context, req *proto.LoadRequest, rsp *proto.LoadResponse) error
	Save(ctx context.Context, req *proto.SaveRequest, rsp *proto.SaveResponse) error
}
