// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: service.proto

package servicepb

import (
	context "context"
	proto "go.unistack.org/micro-config-service/v3/proto"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	ConfigName = "Config"

	ConfigEndpoints = []api.Endpoint{}
)

func NewConfigEndpoints() []api.Endpoint {
	return ConfigEndpoints
}

type ConfigClient interface {
	Load(ctx context.Context, req *proto.LoadRequest, opts ...client.CallOption) (*proto.LoadResponse, error)
	Save(ctx context.Context, req *proto.SaveRequest, opts ...client.CallOption) (*proto.SaveResponse, error)
}

type ConfigServer interface {
	Load(ctx context.Context, req *proto.LoadRequest, rsp *proto.LoadResponse) error
	Save(ctx context.Context, req *proto.SaveRequest, rsp *proto.SaveResponse) error
}
