// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v5.0.0-20260513173418-586c53efa787+dirty

package servicepb

import (
	protojson "google.golang.org/protobuf/encoding/protojson"
)

var (
	marshaler = protojson.MarshalOptions{}
)

func (m *Error) Error() string {
	buf, _ := marshaler.Marshal(m)
	return string(buf)
}
