// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v6.33.4
// source: service.proto

package servicepb

import (
	context "context"
	client "go.unistack.org/micro/v4/client"
)

var (
	ConfigName = "Config"
)

type ConfigClient interface {
	Load(ctx context.Context, req *LoadRequest, opts ...client.CallOption) (*LoadResponse, error)
	Save(ctx context.Context, req *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
}

type ConfigServer interface {
	Load(ctx context.Context, req *LoadRequest, rsp *LoadResponse) error
	Save(ctx context.Context, req *SaveRequest, rsp *SaveResponse) error
}
