// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.0.2
// - protoc              v4.23.4
// source: service.proto

package servicepb

import (
	context "context"
	_ "go.unistack.org/micro/v4/client"
	options "go.unistack.org/micro/v4/options"
)

var (
	ConfigServiceName = "ConfigService"
)

type ConfigServiceClient interface {
	Load(ctx context.Context, req *LoadRequest, opts ...options.Option) (*LoadResponse, error)
	Save(ctx context.Context, req *SaveRequest, opts ...options.Option) (*SaveResponse, error)
}

type ConfigServiceServer interface {
	Load(ctx context.Context, req *LoadRequest, rsp *LoadResponse) error
	Save(ctx context.Context, req *SaveRequest, rsp *SaveResponse) error
}
